#!/usr/bin/env node
var yargs            = require('yargs');
var fs               = require("fs");
var svg2png          = require('svg2png');
var imagemin         = require('imagemin');
var imageminPngquant = require('imagemin-pngquant');


var argv = yargs
  .describe('width', 'Width of output image')
  .describe('height', 'Height of output image')
  .argv;


var input  = process.cwd()+"/"+argv._[0];
var output = process.cwd()+"/"+argv._[1];

console.error("%s -> %s", input, output)

var raw = fs.readFileSync(input);

var opts = {
  plugins: [
    imageminPngquant({quality: '100'})
  ]
}

var svgOpts = {
  width: argv.width,
  height: argv.height
}

svg2png(raw, svgOpts)
  .then(function(data) {
    return imagemin.buffer(data, opts);
  })
  .then(function(data) {
    fs.writeFileSync(output, data);
  })
  .catch(function(err) {
    console.error("Err:", err);
  })


